Repository Nexters/Donmani-Server, pull requests merged in 2025-04, with the labels that each got.

#43 [hotfix] 무지출 데이터 예외처리
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
Labels: bug

#44 #42
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
Labels: bug

#46 [feat] FCM 메시지 푸시 기능 수정 (key 변경)
  .github/workflows/cd.yml
  build.gradle
  src/main/java/donmani/donmani_server/common/config/FirebaseConfig.java
  src/main/java/donmani/donmani_server/fcm/contorller/FCMController.java
  src/main/java/donmani/donmani_server/fcm/service/FCMService.java
Labels: enhancement

#50 [fix] 푸시 수정 및 스웨거 설정 변경
  src/main/java/donmani/donmani_server/common/config/FirebaseConfig.java
  src/main/java/donmani/donmani_server/common/config/OpenAPIConfig.java
  src/main/java/donmani/donmani_server/fcm/service/FCMService.java
Labels: bug

#53 [fix] key json encode&decode 방식으로 변경
  .github/workflows/cd.yml
Labels: bug

#54 #48 [fix] 인코딩/디코딩 키값
  .github/workflows/cd.yml
Labels: bug

#58 Hotfix 57
  src/main/java/donmani/donmani_server/webhook/repository/WebHookRepository.java
  src/main/java/donmani/donmani_server/webhook/service/WebHookService.java
Labels: bug

#59 #57 디스코드 웹훅 오류 수정
  src/main/java/donmani/donmani_server/webhook/repository/WebHookRepository.java
  src/main/java/donmani/donmani_server/webhook/service/WebHookService.java
Labels: bug

#55 [refactor] 월별 요약에서 열린 달 기록없어도 0으로 내려주도록 변경 + 푸시 쿼리 수정
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/fcm/reposiory/PushExpenseRepository.java
  src/main/java/donmani/donmani_server/fcm/service/FCMService.java
Labels: bug, enhancement

#60 #48 월별 요약에서 열린 달 기록없어도 0으로 내려주도록 변경 + 푸시 쿼리 수정
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/fcm/reposiory/PushExpenseRepository.java
  src/main/java/donmani/donmani_server/fcm/service/FCMService.java
Labels: bug

#61 [fix] 스케쥴러 기준 시각 변경 #57
  src/main/java/donmani/donmani_server/webhook/controller/WebHookController.java
Labels: enhancement

#62 스케쥴러 기준 시각 변경
  src/main/java/donmani/donmani_server/webhook/controller/WebHookController.java
Labels: enhancement
