Repository Nexters/Donmani-Server, pull requests merged in 2025-06, with the labels that each got.

#75 [Feature] 동기부여 리워드 기능 개발, 피드백 기능 싱크
  .github/workflows/ci.yml
  build.gradle
  src/main/java/donmani/donmani_server/common/config/NcpStorageConfig.java
  src/main/java/donmani/donmani_server/expense/controller/ExpenseController.java
  src/main/java/donmani/donmani_server/expense/dto/ExpenseResponseDTO.java
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/feedback/controller/FeedbackController.java
  src/main/java/donmani/donmani_server/feedback/dto/FeedbackOpenResponseDTO.java
  src/main/java/donmani/donmani_server/feedback/repository/FeedbackRepository.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
  src/main/java/donmani/donmani_server/reward/controller/RewardController.java
  src/main/java/donmani/donmani_server/reward/dto/FileDTO.java
  src/main/java/donmani/donmani_server/reward/dto/HiddenUpdateRequestDTO.java
  src/main/java/donmani/donmani_server/reward/dto/RewardCheckDTO.java
  src/main/java/donmani/donmani_server/reward/dto/RewardItemResponseDTO.java
  src/main/java/donmani/donmani_server/reward/dto/RewardItemSaveRequestDTO.java
  src/main/java/donmani/donmani_server/reward/entity/RewardCategory.java
  src/main/java/donmani/donmani_server/reward/entity/RewardItem.java
  src/main/java/donmani/donmani_server/reward/entity/UserEquippedItem.java
  src/main/java/donmani/donmani_server/reward/entity/UserItem.java
  src/main/java/donmani/donmani_server/reward/repository/RewardItemRepository.java
  src/main/java/donmani/donmani_server/reward/repository/UserEquippedItemRepository.java
  src/main/java/donmani/donmani_server/reward/repository/UserItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/FileService.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
  src/main/java/donmani/donmani_server/user/controller/UserController.java
  src/main/java/donmani/donmani_server/user/entity/User.java
  src/main/java/donmani/donmani_server/user/service/UserService.java
  src/test/java/donmani/donmani_server/DonmaniServerApplicationTests.java
  src/test/resources/application-test.properties
Labels: bug, enhancement

#82 [fix] 날짜 확인 조건 오류 수정
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#84 [hotfix] 장착한 아이템 쿼리 조회
  src/main/java/donmani/donmani_server/reward/repository/UserEquippedItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#86 reward 기능 내 에러 사항 수정
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/reward/dto/RewardItemResponseDTO.java
  src/main/java/donmani/donmani_server/reward/entity/RewardItem.java
  src/main/java/donmani/donmani_server/reward/repository/UserEquippedItemRepository.java
  src/main/java/donmani/donmani_server/reward/repository/UserItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#89 Dev
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#91 Feature 90
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/feedback/provider/FeedbackTemplateProvider.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#93 Hotfix 81
  src/main/java/donmani/donmani_server/reward/dto/RewardItemResponseDTO.java
  src/main/java/donmani/donmani_server/reward/dto/RewardItemSaveRequestDTO.java
  src/main/java/donmani/donmani_server/reward/entity/RewardCategory.java
  src/main/java/donmani/donmani_server/reward/entity/RewardItem.java
  src/main/java/donmani/donmani_server/reward/entity/UserEquippedItem.java
  src/main/java/donmani/donmani_server/reward/repository/RewardItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#98 Feature 95
  src/main/java/donmani/donmani_server/feedback/provider/FeedbackTemplateProvider.java
Labels: enhancement

#97 Reward 이슈 대응
  src/main/java/donmani/donmani_server/common/exception/GlobalExceptionHandler.java
  src/main/java/donmani/donmani_server/common/exception/HiddenItemAlreadyOpenedException.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug
