Repository Nexters/Donmani-Server, pull requests merged in 2025-07, with the labels that each got.

#100 [fix] 최초 장착의 경우 엔터티 생성으로 수정
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#102 fix : 꾸미기 엣지 케이스 수정
  src/main/java/donmani/donmani_server/reward/repository/UserEquippedItemRepository.java
  src/main/java/donmani/donmani_server/reward/repository/UserItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#103 Dev
  src/main/java/donmani/donmani_server/reward/repository/UserEquippedItemRepository.java
  src/main/java/donmani/donmani_server/reward/repository/UserItemRepository.java
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#107 Dev
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: bug

#108 [hotfix] 아이템 조회 쿼리 오류 수정 (where 조건)
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
  src/main/java/donmani/donmani_server/reward/repository/UserItemRepository.java
Labels: bug

#113 Feature 112
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
Labels: bug

#114 Dev
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
Labels: bug

#116 Feature 115
  src/main/java/donmani/donmani_server/reward/service/RewardService.java
Labels: enhancement

#122 Dev
  src/main/java/donmani/donmani_server/feedback/repository/FeedbackRepository.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
Labels: documentation

#123 [fix] 리워드 레드돗 로직 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
  src/main/java/donmani/donmani_server/user/controller/UserController.java
  src/main/java/donmani/donmani_server/user/entity/User.java
  src/main/java/donmani/donmani_server/user/service/UserService.java
Labels: bug

#126 Feature 125
  src/main/java/donmani/donmani_server/expense/service/ExpenseService.java
  src/main/java/donmani/donmani_server/feedback/service/FeedbackService.java
Labels: enhancement
